aws_region                = "us-east-1"
account_id                = "533267394432"
alb_name                  = "backend-stack-alb"
damain_name               = "dev-backend"
cloudflare_secret_name    = "cloudflare-api-key"
cloudflare_zone_name      = "twinciti.com"
