apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.name }}
spec:
  amiFamily: {{ .Values.amiFamily }}
  role: {{ .Values.iamRoleName }}
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: {{ .Values.deviceName }}
      ebs:
        volumeSize: 1000Gi # Big disk for gen AI models
        volumeType: gp3
        encrypted: true
  subnetSelectorTerms:
    - tags:
        Name: {{ .Values.subnetname }}-vpc-public*  # Name of the Subnets to spin up the nodes
  securityGroupSelectorTerms:                     # required, when not using launchTemplate
    - name: {{ .Values.clusterName }}-node*     # Name of the SecurityGroup to be used with Nodes
  tags:
    InstanceType: {{ .Values.name }}
    Name: {{ .Values.instanceName }}