apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        provisioner: {{ .Values.name }}
        NodeGroupType: {{ .Values.name }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.taints }}
      taints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: {{ .Values.name }}
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "spot", "on-demand" ]
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          {{- with .Values.instanceFamilies }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
  limits:
    cpu: 1000 # CPU Cores across all instances
    memory: 20000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
